### ISSUE TITLE
r-base minimum version should be parsed from CRAN

### ISSUE THREAD

**Issue by russHyde** [bgruening/conda_r_skeleton_helper#23]
Hi,
I was wondering whether the run.[py|R] scripts should identify the minimum version of R that is required by a package and include that in the meta.yaml that is produced. 

For example, when I `run.py` for `plotly`, the minimum-required-versions are extracted for all imported packages (eg,ggplot2 / lazyeval) stated on it's CRAN page, but, although r-base is added to meta.yaml as a requirement, the minimum version of r-base (>=3.2.0) is not added to meta.yaml (and there are R versions that precede this available through anaconda).
All the best

**Comment by jdblischak** [comment]
Hi @russHyde. Good question. This behavior is controlled by the official CRAN skeleton. Here's the explanation ([source](https://github.com/conda/conda-build/blob/7b3b0ac4e53b620c168c19e502dd3ef4985af8bb/conda_build/skeletons/cran.py#L1260)):

```
# We don't include any R version restrictions because
# conda-build always pins r-base and mro-base version.
```

In other words, `conda` isn't designed to really handle the use case you describe with minimum R versions for plotly and other packages. In practice the problem doesn't arise much because we mainly build new conda packages for recent versions of R.

**Comment by russHyde** [comment]
Thanks
